### ISSUE TITLE
Litecoin - HD key magic bytes do not match network magic bytes

### ISSUE THREAD

**Issue by mariodian** [Bit-Wasp/bitcoin-php#125]
I'm trying to generate wallet addresses based on XPUB I got from electrum-LTC. 

Here's what I do (real XPUB from my wallet):

```
$network = NetworkFactory::litecoin();
$xpub = 'xpub661MyMwAqRbcFg6poD2ucZRPwoNpk9CLYwNvoZCGUp1Y6eYNoN64LryZuxDdnm9XViSoSbaspae4yHXAmVVFNJmXbPce1RY4aUDdZiSTBaQ';
$hk = HierarchicalKeyFactory::fromExtended($xpub, $network);

$master = $hk->derivePath("0/0");
$address = $master->getPublicKey();

echo $address->getAddress()->getAddress();
```

It produces this error:

```
An uncaught Exception was encountered

Type: InvalidArgumentException

Message: HD key magic bytes do not match network magic bytes

Filename: <path to my project>/bitcoin-php/Serializer/Key/HierarchicalKey/HexExtendedKeySerializer.php

Line Number: 98

Backtrace:

File: <path to my project>/bitcoin-php/Serializer/Key/HierarchicalKey/HexExtendedKeySerializer.php
Line: 117
Function: fromParser

File: <path to my project>/bitcoin-php/Serializer/Key/HierarchicalKey/ExtendedKeySerializer.php
Line: 43
Function: parse

File: <path to my project>/bitcoin-php/Key/Deterministic/HierarchicalKeyFactory.php
Line: 67
Function: parse

File: <path to my project>/myscript.php
Line: 46
Function: fromExtended
```

The above code works perfectly fine when using bitcoin network and XPUB from my bitcoin Electrum wallet. 

P.S. I tried to add dogecoin network to NetworkFactory class and it gave me the same exact error though I believe the values are correct.

```
public static function dogecoin()
{
 $network = NetworkFactory::create('1e', '16', '9e')
                    ->setHDPubByte('02fd3929')
                    ->setHDPrivByte('02fd3955')
                    ->setNetMagicBytes('c0c0c0c0');
}
```

**Comment by afk11** [comment]
Reviewing now, it appears @rubensayshi added those. I'm not sure if there is a problem yet, however.

>      base58Prefixes[EXT_PUBLIC_KEY] = list_of(0x04)(0x88)(0xB2)(0x1E);
>      base58Prefixes[EXT_SECRET_KEY] = list_of(0x04)(0x88)(0xAD)(0xE4);
https://github.com/litecoin-project/litecoin/blob/master-0.10/src/chainparams.cpp#L167

It appears that chainparams.cpp and my NetworkFactory don't match. The ones from litecoins chainparams.cpp file appear to be those from bitcoin! This probably makes sense, because altcoins normally will not usually rebrand values that aren't used or shown to users in any way. 

Coins typically adopt their own base58 prefixes. If you check http://bip32.org/ you'll see the litecoin private and public key bytes are 019d9cfe and 019da462 respectively. I'm not sure if this is official, but I'm inclined to think so!

Looking at more LTC rebranded software (https://github.com/Someguy123/bitcore/blob/master/lib/networks.js) it appears either (i) there is no consensus on what the prefixes should be for litecoin, or, this guy wasn't aware of other bytes. 

I'll happily accept a PR remedying this if you can find a document outlining what should be used. Perhaps reverting the bytes to bitcoin's is best? 

@rubensayshi if you have any ideas, let us know!

**Comment by mariodian** [comment]
I think private and public key bytes are right (at least it seems everybody uses those), but for some reason different softwares use different network IDs. The [official wiki](https://litecoin.info/Developer_table) says it should be FBC0B6DB for the livenet, the above javascript code uses testnest number for the livenet instead and you use bitcoin's network magic no.

I tried all kinds of values though and nothing worked for me. The funny thing is I could generate some addresses using litecoin's xpub on viacoin's network.

**Comment by afk11** [comment]
@mariodian Comparing the bytes (NetworkFactory) viacoin is using the same as bitcoin. It wouldn't be strange to do this, since the public/private keys are equally valid on all networks. Only issue is that viacoin and litecoin have different address bytes!

You're right there's something wrong with the litecoin network magic ID. Funnily enough, the litecoin wiki is wrong, the value up the top for Magic No is incorrect. It should be this.

>        pchMessageStart[0] = 0xfb;
>        pchMessageStart[1] = 0xc0;
>        pchMessageStart[2] = 0xb6;
>        pchMessageStart[3] = 0xdb;
> (from the chainparams.cpp file linked above)

Will PR this fix in a few. I'm going to ask on #litecoin about the bip32 bytes. May as well get the official word on this.

**Comment by afk11** [comment]
FYI - https://github.com/Bit-Wasp/bitcoin-php/pull/133 PR fixing the network magic bytes. 

Still no answer from #litecoin on the correct HD bytes. If you can find enough indication to use one set over the other I'll work with that.

**Comment by mariodian** [comment]
It seems [priv/pub bytes are right](https://litecointalk.org/index.php?topic=18608.msg262283#msg262283), but you have to use "LTUB" instead of "XPUB" as a master public key. If you want to use XPUB format you have to use Bitcoin's mainnet priv/pub bytes, otherwise it throws "**HD key magic bytes do not match network magic bytes**" error.

However no matter which combination I use, I still get an address starting with "1" instead of "L". Example:

```
MPK = 'Ltub2SSUS19CirucW3NmPh2uURXd2bhPVviUgDauddwNrJrEq2BBTNaoAWU1GpjfTAYn5vrP2iyRfcHT5NtHgPahDEYwtXW6g7J74xyyUEoP82k';
HDPubByte = '019da462';
HDPrivByte = '019d9cfe';
```

```
MPK = 'xpub661MyMwAqRbcFg6poD2ucZRPwoNpk9CLYwNvoZCGUp1Y6eYNoN64LryZuxDdnm9XViSoSbaspae4yHXAmVVFNJmXbPce1RY4aUDdZiSTBaQ';
HDPubByte = '0488b21e';
HDPrivByte = '0488ade4';
```

The result is always 19kg7SadZgHCUvvqw6G6jTSwujTfYcX5UW for derivation path of "m/0/0", but should be LTydNetTeLXFjjd17EFQ1UWi7wpwgqofkJ instead.

**Comment by afk11** [comment]
There's either a bug or you haven't changed the '00' byte somewhere.  Can you paste what you're using for your Network? Or complete example?

**Comment by mariodian** [comment]
NetworkFactory.php:
```
public static function litecoin()
{
        $network = self::create('30', '05', 'b0')
            ->setHDPubByte('019da462')
            ->setHDPrivByte('019d9cfe')
            ->setNetMagicBytes('dbb6c0fb');

        return $network;
}
```

Mycode.php:
```
$xpub = 'Ltub2SSUS19CirucW3NmPh2uURXd2bhPVviUgDauddwNrJrEq2BBTNaoAWU1GpjfTAYn5vrP2iyRfcHT5NtHgPahDEYwtXW6g7J74xyyUEoP82k';
$network = NetworkFactory::litecoin();
$hk = HierarchicalKeyFactory::fromExtended($xpub, $network);
$master = $hk->derivePath("0/0");
$address = $master->getPublicKey();

echo $address->getAddress()->getAddress();
```

Gives me 19kg7SadZgHCUvvqw6G6jTSwujTfYcX5UW and I think it should give me a litecoin address (LTydNetTeLXFjjd17EFQ1UWi7wpwgqofkJ) instead.

**Comment by afk11** [comment]
Ah - you should pass $network to the second `getAddress` call. The network byte is only a serialization concern, so it's not needed before then. Otherwise, it just uses the default. 

If your project is strictly litecoin, you can do `Bitcoin::setNetwork($network)` to override this default!

**Comment by mariodian** [comment]
Oh thank you it's working now. Is there, by any chance, a documentation available for most common use-cases? I mostly go through the code because my knowledge of bitcoin/altcoin protocol is limited, so I'm always missing something.

**Comment by afk11** [comment]
Great! Not so much, there is just the PHPDoc in the code which I try to keep as specific as possible. A helpful IDE will get you most of the way, but I appreciate that it won't help newcomers much. 

I have a vague idea where to start. Do you use documentation generators, or what would you have in mind? I agree some examples would be nice, especially the global settings like this.

**Comment by murich** [comment]
Have same issue with Dash now.
