### ISSUE TITLE
How to get amount of bitcoins on given address using your library?

### ISSUE THREAD

**Issue by gustawdaniel** [Bit-Wasp/bitcoin-php#484]
I asked in stackexchange, but after this I thought that there is better place for this question.

> https://bitcoin.stackexchange.com/questions/53491/how-to-get-amount-of-bitcoins-on-given-address-php-wasp

**Comment by afk11** [comment]
I think it's important that this library doesn't come with such an ability, because it would be vendor specific code. Normally you have some infrastructure tracking UTXO's, or you query a data API. 

You could check this library out: https://github.com/Bit-Wasp/stratum-php it can lookup and talk to Electrum servers (the wallet uses them), query balances within recent (10000 blocks I think). The catch is it uses react-php, so might be a learning curve there.

You could also use an API that offers webhooks so you receive POST messages to your HTTP application. It means you don't have to continuously poll for updates, you just write an endpoint to respond to the messages.  

Blocktrail offers webhooks, has a PHP SDK (which happens to use this library) and has a data API to look up historical data, it should be enough to cover you!
