### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by punto-** [Bit-Wasp/bitcoin-php#515]
Hi, I tried the command mentioned in the README to install, I get this error:

  Problem 1
    - Installation request for bitwasp/bitcoin v0.0.33.2 -> satisfiable by bitwasp/bitcoin[v0.0.33.2].
    - bitwasp/bitcoin v0.0.33.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.

Is there a  way to install manually without the "composer" tool? Also I only need the BIP32 address generation part, is there a way to install only that code in my server?

Thanks!

**Comment by punto-** [comment]
update: I was able to install, the gmp thing is a binary extension so it had to be installed via the distro's package manager, not provided by "composer".

**Comment by afk11** [comment]
Of course - composer doesn't install PHP extensions :) it fills a vital role in managing dependencies and checking that the environment supports the various requirements (CPU architecture, extensions, etc). 

If you want to deploy without using composer, ensure the environment is 'ready', run composer install locally (obviously your environment should match so far as PHP version/extensions) and upload the composer.lock & vendor folder to the server, and make sure to run your applications tests (because you won't know what changes each time, or if it's compatible with your environment, unless you run `composer install` on that server)
