### ISSUE TITLE
How to generate a new address

### ISSUE THREAD

**Issue by Xmaksss** [Bit-Wasp/bitcoin-php#552]
How I can generate new address? Every time I get the same address. What is wrong?
`$network = NetworkFactory::bitcoin();`
`$privateKey = PrivateKeyFactory::fromWif("my_wif");`
`$publicKey = $privateKey->getPublicKey();`
`$address = $publicKey->getAddress()->getAddress($network);`
`echo " - Address: " . $address;`

**Comment by afk11** [comment]
Good question. The address you're making here is a P2PKH address (pub-key-hash address). These addresses are simply an encoding of the hash of your public key, which only has one form. In your example, you have are decoding just a single private key, so it's bound to be the same in this case. 

(By the way, there is a BC break upcoming that will remove the PublicKeyInterface::getAddress() function, because there are now two types of public key address! The safest thing is to use `$address = new PayToPubKeyHashAddress($publicKey->getPubKeyHash())` for now)

In general, good bitcoin practices include rotating this key every time you make a transaction. It can be a pain to manage thousands of unrelated private keys (and backing them up), so if you're looking for a way to generate endless bitcoin addresses, maybe look into BIP32, which the library also supports. 

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php 

All the addresses are derived from a single seed, so you don't back anything up after you create the wallet (the seed, plus knowing the 'bip32 path', and address type used, is enough for recovery)

You can do things like:
```php
See this example to start: https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/bip32.php
$addr0 = $hardened2->deriveChild(0);
$addr1 = $hardened2->deriveChild(1);
$addr2 = $hardened2->deriveChild(2);
```

**Comment by Xmaksss** [comment]
Thank you very much!
I correctly understood that if I want to create a multi-wallet purse then for each user I need to generate a master seed, then the master node, so the accounts, chains and addresses? Or should I have one master seed and master node?

**Comment by afk11** [comment]
It depends what you're trying to do - users are normally responsible for their own master seeds and private keys.. does your server need private keys (a live wallet of sorts), or can it maybe users can submit their own xpub?

**Comment by Xmaksss** [comment]
I want users to create their own wallet and use them without problems. Analogic [blockchain.info](https://blockchain.info).
As far as I know, the blockchain.info is stored xprv and xpub keys and you can get them at any time.
Interact with the network I will be through the [bitcoin-core](https://bitcoin.org/en/developer-guide).

**Comment by afk11** [comment]
I guess you can use watch-only addresses with Bitcoin Core, but in general, your service shouldn't have access to user private keys! Your service becomes a huge central point of failure - you can go rogue, meaning users have to trust you like they do a bank. 

For BC.I I know the client-side device (browser/mobile phone) is the only place that private keys are exposed. The service never has the naked xprv (comes from the recovery mnemonic), BC.I mightn't even have the xpub.. It's all encrypted by the users device, and decrypted the next time they log in.

**Comment by Xmaksss** [comment]
I understood. Thank you very much!
