### ISSUE TITLE
Q: How to mark as Replace-by-fee?

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Bit-Wasp/bitcoin-php#565]
Hello.

How to mark transaction as Replaceable-by-fee?

Link to more info about the feature: https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki

**Comment by afk11** [comment]
Hi, so it's possible to detect the transaction which opts into RBF since an input sequence will be < INPUT_SEQUENCE_MAX. `TransactionInput::isFinal(): bool` tells you this

You won't be able to detect 0conf spends that don't opt into RBF as replaceable, unless you bobserve the RBF-optin transaction, then mark all child transactions in the tree as replacable until the RBF transaction confirms or is replaced.

**Comment by Vasiliy-Bondarenko** [comment]
@afk11 , Hi. I don't need to detect RBF, I need to mark my transaction as RBF. I construct it with TxBuilder and after that broadcast to network.

**Comment by afk11** [comment]
Oh, I see. When building the transaction, set the inputs sequence to a `value < 0xfffffffe`.

```php
$txBuilder->spendOutPoint($utxo->getOutPoint(), null, $sequence);

or 

$txBuilder->input($txid, $vout, null, $sequence);
```

Then you sign & broadcast. To replace the transaction, you need adhere to BIP125, but essentially it means adding an input to bump the fee and bumping the sequence number of existing inputs by one or more.

I put together an automated test for regtest, you can also run these scenarios on your dev machine by calling `BITCOIND_PATH=/path/to/bitcoind vendor/bin/phpunit -c phpunit.rpc.xml`

**Comment by Vasiliy-Bondarenko** [comment]
@afk11 , thanks. it's a little more clear now :)
one more question - can $sequence be just any positive integer like 0x1?
if i retransmit transaction it should be in any arbitrary larger number like 0xf?
should it be hex or can be dec?

can you recommend some tutorial or learning course on the whole bitcoin subject or may be even bit-wasp/bitcoin-php tutorial in particular? :) I started working in this industry, but still have a lot of questions and I don't want to annoy people with them :)

Thank you.

**Comment by afk11** [comment]
The tx structure is documented here: https://en.bitcoin.it/wiki/Protocol_documentation#tx

Yea, the sequence can be any positive integer from 0x0 -> 0xffffffff (uint32 max) is valid. Pass them as scalar integers (`int|string`), but not a hex string, that could cause problems. 

Yea I'm not sure - I did most of my learning by reading https://en.bitcoin.it, the https://github.com/bitcoin/bitcoin repo, and looking at how different libraries implemented the specs. https://bitcoin.org has some developer oriented documentation around the protocol as well. 

Another good place is the BIP's repo, which covers a lot of changes.. Just reading through all the ones roughly related to your areas of interest is a nice way to get acquainted with it all. IRC is often helpful as well if you have a quick question and need some help (#bitcoin, #bitcoin-dev, #bitcoin-wizards, #bitcoin-core-dev) 

You can always post here too, but make sure you've looked into what you're trying to do first :) a lot of "how do I build a wallet" questions tend to go unanswered because it's too broad, and has too many possible answers :P but specific questions are great, and usually worth adding as an example anyways.

**Comment by afk11** [comment]
Did you resolve this issue?

**Comment by Vasiliy-Bondarenko** [comment]
Oh, yes. Sorry, i forgot to close the issue.
Thanks a lot.
