### ISSUE TITLE
Extend WIF format for BIP32 master (extended) keys for SegWit

### ISSUE THREAD

**Issue by gits7r** [Bit-Wasp/bitcoin-php#576]
At this moment this library supports BIP32 extended keys (xpub... mainnet and tpub... testnet). The BIP for WIF format has not been updated yet, it's ongoing discussion, but some wallets extended WIF format for extended keys in order to avoid accidental usage between legacy addresses and native p2wpkh or p2wsh (bench32) addresses.

After the base58 encoded extended key is converted to binary, the first byte encodes the type:
128 + 0 - p2pkh -- xpub... / xprv...
128 + 1 - p2wpkh -- zpub... / zprv...
128 + 2 - p2wpkh-in-p2sh -- ypub... / yprv...
128 + 5 - p2sh
128 + 6 - p2wsh -- Zpub... / Zprv...
128 + 7 - p2wsh-in-p2sh -- Ypub... / Yprv...

The rest remains the same. It would be nice if this library would accept zpub... / zprv... strings and be able to call key generation functions without getting validation failures.

The change will not affect in any way legacy use cases. It will just allow users to use zpub or ypub extended keys without having to hack the first byte before bitcoin-php considers it valid.

I don't know if / when the BIP will be updated, so it's to be decided if this change will happen or not. My thinking is that, if it's not a standard, the majority will never use a zpub, but the very few who would, can do it with this library.

**Comment by afk11** [comment]
Interesting - guessing 128+5 is P2SH|P2PKH since p2wpkh-in-p2sh is already there?

Would be interested to know if there's a BIP or specification document somewhere?  http://docs.electrum.org/en/latest/seedphrase.html#list-of-reserved-numbers IIRC electrum might have posted about this first on the ML..

**Comment by gits7r** [comment]
I am unaware of other documentation besides what I've included here. This was sent on the ML
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/014931.html

And this is another discussion:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/014907.html

Could be good to have this, so we can link zpub/zprv and Zpub/Zprv with bench32 / bip173 for example. But there will be cases where wallets that do not modify the serialization of the extended key provide native segwit bench32 addresses derived from xpub/xprv. So, better make this a feature that will work only when explicitly asked along with a function.

**Comment by afk11** [comment]
I agree for sure, I removed 'getAddress' from HierarchicalKey a while back because it left us no way to change defaults, and I couldn't really expect consumers to be ready to switch to bech32 because some day I felt like tweaking it..  So I do like the feature, it means we can subclass HierarchicalKey to store the prefix or better, the script-type, so we can expose 'getAddress' once again on this new class. 

People using `HierarchicalKey::fromExtended()` would fail on ypubs, etc and would have to create scripts, then addresses, themselves. But people opting into `HierarchicalKey::fromVersionedKey` (name tbd :P) would succeed, and be able to generate the address without worrying about the script or address type specifics.

I think I'd need to revise some of the Network class to deal with this, though it shouldn't take much.. Think it now needs to contain a list of script-types w/ associated versions, so you can't accidentally re-encode the key to another network that doesn't have segwit for example.. 

I hadn't expected networks to diverge much, but segwit is a good reason to be careful with this in case software happily continues to work and you wind up funding segwit outputs on BCH or something.

**Comment by gits7r** [comment]
Fully agreed on all aspects.  It is the best option to allow all these different script types, since we try to make it easy for people to entirely switch to bench32 addresses as soon as possible, even though the process might take some time. Being able to use this library with an ypub/yprv and zpub/zprv derived keys would be nice.

**Comment by gits7r** [comment]
@afk11 what do you think the best approach will  be here extend 'bitcoin' network interface settings to support zpub,ypub or remove network? also, we lack instructions on how one can extend network class for their own network (magicbytes, prefix, where are these defined?).

**Comment by afk11** [comment]
I started refactoring Network so we can be a bit more flexible about the types of features we can support.  https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Network/Network.php#L31-L40 Mostly anticipating this kind of stuff 

Thinking of writing something similar to ExtendedKeySerializer and allow callers to specify their own supported bytes for now.. can look at exposing something on Network to serve this class then?

For custom networks you gotta check out the coins chainparams.cpp for the various magic bytes and main.cpp/validation.cpp for signed message magic.  

The recent changes to Network (#583) are mostly about gracefully handling features that aren't available on other networks (like bech32, or some of these script prefixes)

**Comment by gits7r** [comment]
yes, but this is how things happened in the ecosystem and there s not much we can do... xpubs are shared between p2sh and p2pkh .. it would be neat to differentiate somehow but not possible without messing up existing implementations and use cases.

so what would the code look like if one wanted to accept zpub extended key on bitcoin mainnet network and generate addresses of m/0/0 with bc1 (p2wpkh) and sha256 (p2wsh)? what files should be edited and how?

**Comment by gits7r** [comment]
Hello Thomas - getting back to this, sorry I know you are busy. I would like to know if in the next release it would be possible to use zpub... / ypub... strings with this library in Bitcoin mainnet network, otherwise I need to implement a tool that takes the zpub, converts it to hex and modifies its first byte and the trailing checksum so the same secp256k1 keys will result in both electrum native segwit (zpub) and this library's variant. Or is it simpler to code a custom Bitcoin network without implementing it to the entire library? I just need your opinion towards the best approach here.

Some people that have online shops for security reasons keep the private keys offline and use this library to generate addresses from an extended key for each invoice. It's hard to keep two sets of seeds, already one is complicated enough for them... because you know, Bitcoin ;)

**Comment by afk11** [comment]
Hey mate! Haven't forgotten about this one, just never settled on an approach. Have it sort of coming together now, hopefully update this in a day or two.

**Comment by afk11** [comment]
Have this from the weekend https://github.com/Bit-Wasp/bitcoin-php/compare/0.0.35...afk11:scripted-hk?expand=1 though a tonne of code was duplicated unnecessarily, still trying to find a harmonious way to get this working with the existing serializer classes.

It pretty much mirrors the API for HierarchicalKey / HierarchicalKeyFactory, except you need to create a ScriptDataFactory to create a key from scratch, and configure a GlobalHdPrefixConfig for serializing.

Will see how things shape up, really want to consolidate all that code before PRing this.

**Comment by afk11** [comment]
@gits7r Decided to do one part differently, check out the tests in this PR and let me know if you see anything missing? #660

**Comment by Gwinest** [comment]
Thomas, is this rep safe against a resigning attack?
As seen in:
https://bitcoin.stackexchange.com/questions/35848/recovering-private-key-when-someone-uses-the-same-k-twice-in-ecdsa-signatures

There was a exchange hack in Brazil, recently, but turns out it was a
failure on the code, and the program exposed the private key to the whole
network.



Em Dom, 4 de mar de 2018 14:12, Thomas Kerin <notifications@github.com>
escreveu:

**Comment by afk11** [comment]
@Gwinest Yep it's safe, it uses deterministic signatures. Also, please open another issue instead of posting on an unrelated thread! (it's also in the docs ;))

**Comment by Gwinest** [comment]
Awesome!
Oh, and sorry for posting as a reply here, I received this as an email and
just replied (it's not Slack! Haha).
Next time I will do it right.

Thanks :)


Em Dom, 4 de mar de 2018 19:43, Thomas Kerin <notifications@github.com>
escreveu:

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/pull/660 This feature landed in 0.0.35. Future issues should go in a new issue :)
