### ISSUE TITLE
Switching to Bitcoin Cash and private keys

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Bit-Wasp/bitcoin-php#585]
Hello.

I'm building multi-network app. When i work with main Bitcoin network i set the network like 
```php
Bitcoin::setNetwork(NetworkFactory::bitcoin());
```
on Litcoin i suppose to switch like
```php
Bitcoin::setNetwork(NetworkFactory::litecoin());
```
Is it correct?

But how to switch to Bitcoin Cash network? I don't see anything like `NetworkFactory::cash()`

And the second question - is it possible to use the same xprv/xpub across all bitcoin networks? Or i must generate separate key pairs for all networks?

Thank you.

**Comment by afk11** [comment]
Bitcoin Cash uses all the same prefixes as bitcoin (for now), so bitcoin is actually suitable to use with it. _However_, you should make a separate bitcoin cash network that doesn't have the segwit HRP thing, otherwise your users when pasting a bech32 address could end up funding that on Bitcoin Cash. 

```php
    /**
     * @return NetworkInterface
     * @throws \Exception
     */
    public static function bitcoin()
    {
        $network = self::create('00', '05', '80')
            ->setHDPubByte('0488b21e')
            ->setHDPrivByte('0488ade4')
            ->setNetMagicBytes('d9b4bef9')
-            ->setSegwitBech32Prefix("bc") # this needs to be removed to safely use bitcoin cash
        ;
        return $network;
    }
```

Aside - you'll run into pains with the global network when you try to unit test your application. Imagine you have a dataprovider where a class calls `Bitcoin::setNetwork` - your tests wouldn't see the same network when they run. I'd suggest you write pure code that passes the Network around, so that your objects addresses & serialization don't depend on global state!

**Comment by afk11** [comment]
Btw, if you want to use networks outside of NetworkFactory that's fine too. Just write a class extending `NetworkInterface` and you can define your own that you keep in your own project.

**Comment by Vasiliy-Bondarenko** [comment]
got it. 
mostly. :))
thank you.
