### ISSUE TITLE
BlockFactory::fromHex() uses a lot of memory

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Bit-Wasp/bitcoin-php#605]
Hello. 

I've found that BlockFactory::fromHex() uses too much memory. While decoding Bitcoin core blocks it's less then 256mb, but when i try to decode Bitcon Cash block I have to limit memory to 1024Mb, which is a lot! 
With less memory limit it fails with
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in /home/vagrant/code/forwarder/vendor/bitwasp/bitcoin/src/Script/Opcodes.php on line 280
```
I think there is a memory leak somewhere.

**Comment by afk11** [comment]
Wow! Please post a block hash you encountered this with (though I guess any block these days is good for benchmarking!)

I'll check this out when I can

**Comment by afk11** [comment]
Having a look now - I am seeing the same thing, though not quite running into the memory error. The TransactionSerializer is probably the most likely place for something small to turn into quite a problem!

```php
$start = memory_get_usage(false);
$vin[] = $this->inputSerializer->fromParser($parser);
$end = memory_get_usage(false);
echo "Inputs diff: " . ($end - $start).PHP_EOL;
```

Something that stands out is that outputs seem to cost as much memory as inputs, which is strange. I would expect outputs to have a much smaller impact.. Using the above for inputs and outputs gives me this output for a particular part of a block:

```
Inputs diff: 9160
Outputs diff: 8920
Outputs diff: 8544
Inputs diff: 9160
Outputs diff: 8928
Outputs diff: 8928
Outputs diff: 8552
Outputs diff: 8928
Outputs diff: 8552
Outputs diff: 8928
Outputs diff: 8928
Outputs diff: 8552
Outputs diff: 8920
Outputs diff: 8552
Outputs diff: 8928
Outputs diff: 8544
Outputs diff: 8920
Outputs diff: 8544
Outputs diff: 8552
Inputs diff: 9160
Outputs diff: 8920
Outputs diff: 8544
```

Inputs and outputs both have a script, and the Opcodes instance is required there.. so I'm betting that we are creating `#opcodes = #inputs+#outputs` of those inputs because each input/output has a script which has opcodes..

I think the serializer should have an Opcodes instance to inject into new instances so we don't run into this..

**Comment by afk11** [comment]
#606 and #607 should fix this, and should reduce memory by 89% or so (according to the block I tested)

Before:
U1: 1117064 - hex block converted to a buffer
U2: 105379264 - parsed same buffer into block

After:
Buffer size: 1037935
U1: 1117064 - hex block converted to buffer
U2: 12451024 - parsed same buffer into block

**Comment by Vasiliy-Bondarenko** [comment]
Reusing Opcodes - this is exactly what I was thinking to try tomorrow :)

**Comment by Vasiliy-Bondarenko** [comment]
Well... it's a lot better now! Thanks a lot.
Anyway I still have one block failing with 256 mb memory limit :)
block 0000000000000000016956ce75c241a301a8b674abc8382a7138afda8c48f453 in Bitcoin bash.
```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 8192 bytes) in /home/vagrant/code/forwarder/vendor/bitwasp/bitcoin/src/Script/Opcodes.php on line 280
```

**Comment by afk11** [comment]
Thanks again for reporting! Tagged as v0.0.34.2
