### ISSUE TITLE
Litecoin bech32 Address

### ISSUE THREAD

**Issue by goodProjects** [Bit-Wasp/bitcoin-php#663]
I'm getting Bitcoin Bech32 as follows:
```
$p2wpkhWP = WitnessProgram::v0($masterkey->derivePath("m/0/1")->getPublicKey()->getPubKeyHash());
$p2wpkh = new SegwitAddress($p2wpkhWP);
$new_address = $p2wpkh->getAddress();
```
am I getting P2WSH or P2WPKH? and how to get P2WSH/Bech32 For Litecoin?

**Comment by afk11** [comment]
> am I getting P2WSH or P2WPKH?

You're getting P2WPKH. A SegwitAddress at the moment is only valid for v0, so depending on the size of your 'program', 20 bytes a hash of a public key so P2WPKH, and 32 bytes means a hash of a script so P2WSH.

> and how to get P2WSH/Bech32 

https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/addresstypes.script.php check the bottom for an example. Check over the source for P2shScript and WitnessScript!

> .....for litecoin

So, there's a few places in the library where we simplify the API for bitcoin. 

https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Address/SegwitAddress.php#L57 getAddress is basically the same for all types of address (besides the encoder). Use a default network if none is provided.

Changing the default is only a good idea if you're writing a 5 line script. I don't recommend (it will cost you time later to refactor; probably a bunch of BC breaks as you add NetworkInterface to some constructors/methods; if you use unit tests against multiple networks, etc. Static is bad..)

The best thing to do in these cases it to go the 'pure function' way. Instead of relying on what amounts to a global variable, you now use a codepath that forces you to provide a network!

```php
function getMyAddress(HierarchicalKey $hk, NetworkInterface $network) {
    $p2wpkhWP = WitnessProgram::v0($masterkey->derivePath("m/0/1")->getPublicKey()->getPubKeyHash());
    $p2wpkh = new SegwitAddress($p2wpkhWP);
    return $p2wpkh->getAddress($network);
}
```

**Comment by goodProjects** [comment]
Thanks a bunch for your help! 

at the bottom of [addresstypes.script.php](https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/addresstypes.script.php#L32) file, What is "pay-to-script-hash | Pay-to-witness-script-hash"? is it the same as P2WSH by size? how usually its used? 

that is my final function, but I think we can do something to get address faster (talking performance) what do you think? 

```
$pubkeyhash = $masterkey->derivePath("m/0/1" )->getPublicKey()->getPubKeyHash();
$script = ScriptFactory::scriptPubKey()->p2pkh($pubkeyhash);
$addrReader = new AddressCreator();
$p2pkh = $addrReader->fromOutputScript($script);
$p2wshScript = new WitnessScript($p2pkh->getScriptPubKey());
$new_address = $p2wshScript->getAddress()->getAddress();
```

Also, Yeah sure I'm setting the required network, Also why don't you remove that default network,
It's making a lot of troubles when I forget to set the network when I'm working with (e.g.) LTC. Throwing an exception instead would be much better.

**Comment by goodProjects** [comment]
It seems to be that LTC testnet has no bech32 address set, BitWasp\Bitcoin\Exceptions\MissingBech32Prefix

**Comment by afk11** [comment]
> What is "pay-to-script-hash | Pay-to-witness-script-hash"? is it the same as P2WSH by size? how usually its used?

On that line we coerce a ScriptInterface into a WitnessScript (making it's output script a p2wsh witness program), and then coercing it into a P2shScript (making it's output script a p2sh script, and the redeemScript is the p2wsh program). The two classes make it a _little_ more safer to deal with the various script types, and exist for convenience too, since they take care of producing the right address.

They can be used on their own, or nested in this way. They also throw an exception if you nest them incorrectly.

Hmm, on performance: elliptic curve stuff is actually the bottleneck! 

Another random point, if you're developing, you may have xdebug installed. This makes the operations _incredibly_ slow, and you won't have xdebug on a production system. Though, if ECC stuff is actually slow maybe think about installing https://github.com/bit-wasp/secp256k1-php.

also, you are returning the p2pkh address of the key in your witnessScsript, but you do _not_ give users that address. The only script you generate addresses from, are scriptPubKeys:

```php
$pubkey = $masterkey->derivePath("m/0/1" )->getPublicKey(); # slowest step by far
$pukeyhash = $pubkey->getPubKeyHash();
$witnessScript = new WitnessScript(ScriptFactory::scriptPubKey()->p2pkh($pubkeyhash));
$address = $p2wshScript->getAddress()->getAddress();

// or: if you only have the scriptPubKey handy..
$scriptPubKey = $p2wshScript->getOutputScript();
$addrReader = new AddressCreator();
$address = $addrReader->fromOutputScript($addrReader);
```

**Comment by afk11** [comment]
> It seems to be that LTC testnet has no bech32 address set, BitWasp\Bitcoin\Exceptions\MissingBech32Prefix

Nice one, just saw the PR and left a comment!

**Comment by goodProjects** [comment]
I will try my best to contribute making this library better! It's time to return the favor!

**Comment by goodProjects** [comment]
Hi, You've mentioned that installing secp256k1-php could improve the performance, Do bitcoin-php know that I've secp256k1-php installed and deal with it?

**Comment by afk11** [comment]
https://github.com/Bit-Wasp/bitcoin-php/blob/master/src/Crypto/EcAdapter/EcAdapterFactory.php#L48 yea buried a few layers deep in the static methods :)

It's way faster anyways, you should give it a look!

**Comment by goodProjects** [comment]
Amazing! I'm just installing it.

**Comment by goodProjects** [comment]
Performance difference is very dissimilar, it was like ~ 3500ms to get three addresses with different networks and paths after secp256k1-php its become 450ms!! Thank you for taking time out and suggesting me this!

**Comment by afk11** [comment]
Cool, awesome! Back a few years ago when mdanter/ecc was much slower and we first explored the extension it was like 8000x faster :D such an amazing lib

What script are you using to benchmark btw? I wrote this up, and am curious where it's spending it's time in that 3500ms!

```php
require_once __DIR__ . "/vendor/autoload.php";

use BitWasp\Bitcoin\Address\PayToPubKeyHashAddress;
use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Script\WitnessScript;
use BitWasp\Bitcoin\Key\Factory\HierarchicalKeyFactory;
use BitWasp\Buffertools\Buffer;

$bytes = new Buffer('abcd1234abcd1234abcd1234abcd1234');
$r = HierarchicalKeyFactory::fromEntropy($bytes);

$pre = microtime(true);
for ($i = 0; $i < 3; $i++) {
    $a = microtime(true);
    $pubkeyhash = $r->derivePath("m/0/1" )->getPublicKey()->getPubKeyHash();
    $script = ScriptFactory::scriptPubKey()->p2pkh($pubkeyhash);
    $addrReader = new AddressCreator();
    $p2pkh = $addrReader->fromOutputScript($script);
    $p2wshScript = new WitnessScript($p2pkh->getScriptPubKey());
    $new_address = $p2wshScript->getAddress()->getAddress();
    echo "t: " . (microtime(true)-$a).PHP_EOL;
}
echo "tot: " . (microtime(true)-$pre).PHP_EOL;
```

**Comment by goodProjects** [comment]
Actually, it was 6 addresses 😅
I have disabled secp256k1.so it took only 1.0052 s even if its disabled.

If I enable it, it took just 300-450ms (with apache connection and non-production server)
before I install it, as I mentioned 3000-3500ms.

I have tagged the lines which is spending the most time.   

```use BitWasp\Bitcoin\Script\ScriptFactory;
use BitWasp\Bitcoin\Address\AddressCreator;
use BitWasp\Bitcoin\Script\WitnessScript;
use BitWasp\Bitcoin\Key\Deterministic\HierarchicalKeyFactory;
use BitWasp\Buffertools\Buffer;
use BitWasp\Bitcoin\Network\NetworkFactory;
use BitWasp\Bitcoin\Bitcoin;




$pre = microtime(true);
for ($i = 0; $i < 6; $i++) {
    $bytes = new Buffer(md5( microtime()));
    $r = HierarchicalKeyFactory::fromEntropy($bytes);
    $a = microtime(true);
    $pubkeyhash = $r->derivePath("m/0/$i" )->getPublicKey()->getPubKeyHash(); // this one.
    //
    if ($i == 0){
        Bitcoin::setNetwork(NetworkFactory::bitcoinTestnet());
    }
    if ($i == 2){
        Bitcoin::setNetwork(NetworkFactory::litecoinTestnet());
    }
    if ($i == 4){
        Bitcoin::setNetwork(NetworkFactory::litecoin());
    }
    $xpub = $r->derivePath("m/44'/0'/0'")->toExtendedPublicKey(); // this one.
    $script = ScriptFactory::scriptPubKey()->p2pkh($pubkeyhash);
    $addrReader = new AddressCreator();
    $p2pkh = $addrReader->fromOutputScript($script);
    $p2wshScript = new WitnessScript($p2pkh->getScriptPubKey());
    $new_address = $p2wshScript->getAddress()->getAddress();
    echo "t: " . (microtime(true)-$a).PHP_EOL;
}
echo "tot: " . (microtime(true)-$pre).PHP_EOL;```
