### ISSUE TITLE
Get inputs addresses from block transactions

### ISSUE THREAD

**Issue by AdvancedStyle** [Bit-Wasp/bitcoin-php#679]
I'm trying to get the addresses from the inputs transactions from raw block hex and this is what I have:

```
$block_hex = '012someblockrawhex....';

        $newBlock = BlockFactory::fromHex($block_hex);
        $block_tx = $newBlock->getTransactions();
        foreach ($block_tx as $tx) {
            $txid = $tx->getTxId()->getHex();

            foreach($tx->getInputs() as $idx => $input){
                $prev_tx = $input->getOutPoint()->getTxId()->getHex(); // OK!
                $prev_n = $input->getOutPoint()->getVout(); // OK!
                try {
                    $address = AddressFactory::fromScript($input->getScript())->getAddress();
                    echo $address."\n"; // Wrong :(
                }catch(Exception $e){}
                }
            }
```

However the address does not match the actual address that funds were sent from; what am I doing wrong?

**Comment by afk11** [comment]
you need output scripts to learn the address :) it's really easy to mischaracterize addresses as simple addresses. I'd suggest you log (txid,vout)=>type when you create the utxos instead of when it's spent.

There's two cases where you learn more info by looking at the spend, which is when it's p2sh or p2wsh, cuz the spend reveals the redeem/witness script, so it tells you which _type_ of P2SH / P2WSH it was.

**Comment by AdvancedStyle** [comment]
Ok just to be 100% clear, you can't find the address from the inputs (getInputs()), but instead would need to get the previous transaction that it was spending, and then look at the getOuts() from that?

**Comment by afk11** [comment]
I would say that's the most complete and reliable method. If you are able to describe why you're trying to learn the address of inputs I might  you in the right direction.

You can work out if it was P2SH or P2WSH, because the last element of the scriptSig / witness would be a script, and probably a 'standard' one. 

P2PK and P2PKH are the most common non-script-hash type, and you can distinguish them from _eachother_, because the scriptSig looks like this, but not from more advanced scripts:
P2PKH: <sig> <pubkey>
P2PK: <sig>

For instance, using the template of the above two would misclassify these scripts..
(as P2PKH) DUP DROP DUP DROP [hash160] HASH160 EQUALVERIFY CHECKSIG
(as P2PK) CLTV 550000 [pubkey] CHECKSIG

Even though they're non-standard, this way of guessing would cause an 1blahblah address to be derived for the NOT-P2PKH script.

**Comment by afk11** [comment]
Hope I gave an account of why it _can_ be unreliable, albeit not 100% unreliable.. but if your workflow isn't one where looking up the (txid,vout) for it's output script comes at a performance penalty, recording it in the block/tx where the output was created is definitely the way to go.

Let me know if you need any help on this anyways, or feel free to close the issue if it's resolved :)
