### ISSUE TITLE
Major changes since 0.0.35 release?

### ISSUE THREAD

**Issue by Crypto2** [Bit-Wasp/bitcoin-php#700]
I'm looking to get started using bitcoin-php but it seems like what's in github master differs a lot from the release composer installs. Is there going to be a new release soon? I'd hate to build something then have to make a ton of changes when the new release comes out.

**Comment by afk11** [comment]
Master includes php7 support and some small changes (static PrivateKeyFactory, HierarchicalKeyFactory classes are now instances)

**Comment by deweller** [comment]
Thanks for your work on this project.  We would like to get a tagged release so we can move up from PHP 7.1 to PHP 7.2+.  Anything I can do to help?

This is related to https://github.com/Bit-Wasp/bitcoin-php/issues/661 for us.

**Comment by afk11** [comment]
Hey guys

I've had some time to think about this again.

I think it's a good time to get the secp256k1-php BC breaks in, since they also include improvements only available in 7.0. They only affect the Secp256k1 EcAdapter components

 - [ ] https://github.com/Bit-Wasp/secp256k1-php/pull/99
 - [ ] https://github.com/Bit-Wasp/secp256k1-php/pull/100
 - [ ] https://github.com/Bit-Wasp/secp256k1-php/pull/101
 - [ ] https://github.com/Bit-Wasp/secp256k1-php/pull/102

They've yet to be merged, I'll do that ASAP, and work can start on dealing with those breaks.I'll write up some docs for 0.0.35 -> next release meanwhile

**Comment by mattdeveluk** [comment]
Would be great to bring support for PHP 7.1+, btw thanks for all your work.

**Comment by afk11** [comment]
Hi folks, finally released 7+ support under v1.0.0. The release notes detail the major differences between it and v0.0.35.x
