### ISSUE TITLE
Light node

### ISSUE THREAD

**Issue by DreamteamOne** [Bit-Wasp/bitcoin-php#748]
Hi,

Do I need to use a full Bitcoin node to use this?

Or is there a light node I can use?

Thank you!

**Comment by afk11** [comment]
Hey, the library is a pure PHP library for dealing with the data structures on the bitcoin network, deriving keys, signing transactions, etc. It's not required to have a full / light node to use anything in this library, which is actually the one consistent design point the library has held since it's conception.

I can suggest the following libraries that make use of the electrum infrastructure: https://github.com/Bit-Wasp/electrum-discovery - discovering BTC electrum servers, and https://github.com/Bit-Wasp/stratum-php a react-php library for async communication with electrum servers.

Otherwise, if you really wanted to go low level, there's a library for p2p networking https://github.com/Bit-Wasp/bitcoin-p2p-php which you could write a full or light client with. 

I could tell you where to look if I knew what you were trying to do, maybe you could explain what you're trying to do?

**Comment by DreamteamOne** [comment]
I would like to do the following please:

1. Generate Bitcoin addresses
2. Transfer funds to addresses
3. Get account balances with # of confirmations

Thank you!

**Comment by afk11** [comment]
1, and 2, you can carry out with the library, with some data. For 3, you could try using https://github.com/Bit-Wasp/stratum-php to query for balances against electrum servers. IIRC you can just query random addresses with them. It's written with react-php, so it's a little different.. but you could probably sync against random electrum servers, or even run your own electrum-personal-server.

**Comment by afk11** [comment]
1, you can do offline, or on a machine with BIP32 xpubs.
2, signing: right, you obviously need to be able to sync transactions, however, note the requirements for signing transactions depends only on what type of wallet you're building. (bip32? bip44? segwit? etc), not on where you sync your data from.
3. syncing: I mentioned electrum because it's something this project has code for, and there are a bunch of servers running already. You don't have to use it, if there are better backends out there, use them!

ultimately, point 3 in your case is a script that watches "some endpoint" for transactions involving addresses from stage 1, and saves them in a database so step 2 knows what coins to spend :)

**Comment by DreamteamOne** [comment]
Thank you very much for your help!

**Comment by afk11** [comment]
Closing this, feel free to open another if something comes up!
