### ISSUE TITLE
zcash update transaction v3 signature

### ISSUE THREAD

**Issue by Vukajlovic** [Bit-Wasp/bitcoin-php#808]
Hi everyone,

There is problem with zcash network.
They updated transaction format version to v3

So, I'm receiving errors after signing transaction.

**Comment by afk11** [comment]
bitcoin-php doesn't support zcash - this probably isn't the right place for your issue

**Comment by Vukajlovic** [comment]
> bitcoin-php doesn't support zcash - this probably isn't the right place for your issue

Wtf ?

It's supporting zcash network  ?!
Probably I'm not saying it right but it supports address creating and transaction creating (signing)

**Comment by afk11** [comment]
I know what you are saying, but to be clear: just because zcash changes something it doesn't mean this library will support it. It's not a general purpose cryptocurrency library, and features for other cryptocurrencies belong somewhere else.

Edit: I'll reopen this for a bit in case anyone can offer help, but long term this isn't the place for such issues.

**Comment by Vukajlovic** [comment]
@afk11 I know that , it's just a question if someone is able to help me with it. That's all...
