### ISSUE TITLE
Warning: gmp_init(): Unable to convert variable to GMP - wrong type

### ISSUE THREAD

**Issue by josecelano** [Bit-Wasp/bitcoin-php#95]
Running this sample:
https://github.com/Bit-Wasp/bitcoin-php/blob/master/examples/offlinetx.p2pkh.testnet.php

I get this warning:
```
Warning: gmp_init(): Unable to convert variable to GMP - wrong type in C:\Users\Jose\Projects\BlockCypher\php-client\vendor\mdanter\ecc\src\Math\Gmp.php on line 281
```

Link to the warning line:
https://github.com/mdanter/phpecc/blob/master/src/Math/Gmp.php#L281

And the problem seems to be this:
https://github.com/mdanter/phpecc/issues/90

(passing double to gmp_init)

**Comment by afk11** [comment]
As mentioned over on mdanter/phpecc#90 - I reckon passing the amount in satoshis passed as a string will solve this. 

PhpEcc assumes that the input and output to math operations are all string|int's. The int value is only when a user happens to pass a valid int, but since it does gmp_strval($a, 10) on everything, output will be strings only, meaning most of the inputs to functions are strings. 

Further to this, you'll probably run into issues if you instantiate a class with an int, serialize it, parse it, and assertEquals($class, $parsedClass), which will compare all properties of the two classes. There will be a type mismatch here, because your first instance has the value as an int, and the parsed instance was given a string instead. 

This is 'safe' because you won't run into any strange PHP behaviour like changing an int to a double because it approaches the machines max integer size. 

So, keep using strings and you won't run into it.

**Comment by afk11** [comment]
Did this clear it up?

**Comment by DeftNerd** [comment]
Wanted to add more info to this issue in case anybody runs across it

bitcoin-php/examples/transactionBuilder.php fails with the same gmp_init() error, but the error only occurs in Windows. This is because there isn't really a version of GMP for Windows. PHP's GMP library on Windows is replaced with MPIR, an opensource library forked from GMP that's supposed to be a drop-in replacement. 

Ubuntu:
PHP Version => 7.0.6-1~dotdeb+8.1
GMP version => 6.0.0

Windows
PHP Version => 7.0.0
MPIR version => 2.7.0 (Fails)

PHP Version => 5.6.16
MPIR version => 2.6.0 (Fails)

There is a MPIR 2.7.2, but only the source is available and I don't have visual studio to compile it to test if it works with phpecc. 

Obviously the problem can be blamed either on MPIR or with the upstream phpecc not taking MPIR into account somehow. 

I only know enough to spot what the problem is, not enough to figure out who the right person to report it to is. 

This bug report doesn't really belong in Bitwasp, but it's worth mentioning in case any devs run across it.
